[2025-06-19T01:17:19.331+0000] {processor.py:161} INFO - Started process (PID=51398) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:17:19.332+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:17:19.333+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.333+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:17:19.336+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.335+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:19.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:17:19.352+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.030 seconds
[2025-06-19T01:17:49.905+0000] {processor.py:161} INFO - Started process (PID=51434) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:17:49.906+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:17:49.907+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.906+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:17:49.909+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.909+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:17:49.925+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.028 seconds
[2025-06-19T01:18:20.351+0000] {processor.py:161} INFO - Started process (PID=51470) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:18:20.352+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:18:20.353+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:18:20.356+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.355+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:20.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:18:20.370+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.028 seconds
[2025-06-19T01:18:51.146+0000] {processor.py:161} INFO - Started process (PID=51512) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:18:51.147+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:18:51.148+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.148+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:18:51.151+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.150+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:51.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:18:51.168+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.030 seconds
[2025-06-19T01:19:21.782+0000] {processor.py:161} INFO - Started process (PID=51548) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:19:21.783+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:19:21.785+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:19:21.788+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.787+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:19:21.805+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.031 seconds
[2025-06-19T01:19:52.375+0000] {processor.py:161} INFO - Started process (PID=51584) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:19:52.376+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:19:52.376+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.376+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:19:52.379+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.378+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:52.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:19:52.394+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.026 seconds
[2025-06-19T01:20:22.799+0000] {processor.py:161} INFO - Started process (PID=51620) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:20:22.800+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:20:22.801+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.801+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:20:22.803+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.802+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:20:22.818+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.027 seconds
[2025-06-19T01:20:53.243+0000] {processor.py:161} INFO - Started process (PID=51656) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:20:53.245+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:20:53.246+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.246+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:20:53.249+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.248+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:53.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:20:53.268+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.033 seconds
[2025-06-19T01:21:24.105+0000] {processor.py:161} INFO - Started process (PID=51692) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:21:24.106+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:21:24.107+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:24.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:21:24.109+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:24.109+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:24.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:21:24.125+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.028 seconds
[2025-06-19T01:21:54.639+0000] {processor.py:161} INFO - Started process (PID=51728) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:21:54.640+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:21:54.640+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:21:54.643+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.642+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:21:54.657+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.025 seconds
[2025-06-19T01:22:25.212+0000] {processor.py:161} INFO - Started process (PID=51764) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:22:25.213+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:22:25.214+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.214+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:22:25.217+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.216+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:25.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:22:25.231+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.028 seconds
[2025-06-19T01:22:56.071+0000] {processor.py:161} INFO - Started process (PID=51800) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:22:56.072+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:22:56.073+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:56.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:22:56.076+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:56.075+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:56.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:22:56.091+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.027 seconds
[2025-06-19T01:23:26.634+0000] {processor.py:161} INFO - Started process (PID=51836) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:23:26.635+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:23:26.636+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.635+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:23:26.638+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.637+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.639+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:23:26.654+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.028 seconds
[2025-06-19T01:23:57.288+0000] {processor.py:161} INFO - Started process (PID=51872) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:23:57.289+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:23:57.290+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.290+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:23:57.294+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.292+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:57.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:23:57.309+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.028 seconds
[2025-06-19T01:24:27.946+0000] {processor.py:161} INFO - Started process (PID=51908) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:24:27.947+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:24:27.947+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.947+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:24:27.950+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.949+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:27.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:24:27.964+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.025 seconds
[2025-06-19T01:24:58.484+0000] {processor.py:161} INFO - Started process (PID=51944) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:24:58.485+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:24:58.485+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.485+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:24:58.488+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.487+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:58.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:24:58.504+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.031 seconds
[2025-06-19T01:25:29.057+0000] {processor.py:161} INFO - Started process (PID=51980) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:25:29.058+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:25:29.059+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:29.058+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:25:29.061+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:29.060+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:29.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:25:29.076+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.027 seconds
[2025-06-19T01:25:59.621+0000] {processor.py:161} INFO - Started process (PID=52016) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:25:59.622+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:25:59.623+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:25:59.626+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.625+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:59.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:25:59.640+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.026 seconds
[2025-06-19T01:26:30.511+0000] {processor.py:161} INFO - Started process (PID=52052) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:26:30.512+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:26:30.513+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.513+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:26:30.515+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.515+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:30.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:26:30.534+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.033 seconds
[2025-06-19T01:27:00.894+0000] {processor.py:161} INFO - Started process (PID=52088) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:27:00.895+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:27:00.896+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:27:00.900+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.899+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:27:00.917+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.030 seconds
[2025-06-19T01:27:31.497+0000] {processor.py:161} INFO - Started process (PID=52124) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:27:31.498+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:27:31.499+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.499+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:27:31.503+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.502+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:31.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:27:31.520+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.031 seconds
[2025-06-19T01:28:02.059+0000] {processor.py:161} INFO - Started process (PID=52160) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:28:02.061+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:28:02.062+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:02.061+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:28:02.064+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:02.064+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:02.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:28:02.082+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.031 seconds
[2025-06-19T01:28:32.764+0000] {processor.py:161} INFO - Started process (PID=52196) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:28:32.765+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:28:32.766+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.766+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:28:32.770+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.769+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:28:32.789+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.034 seconds
[2025-06-19T01:29:03.731+0000] {processor.py:161} INFO - Started process (PID=52232) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:29:03.733+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:29:03.735+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.735+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:29:03.740+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.739+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:03.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:29:03.764+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.044 seconds
[2025-06-19T01:29:33.898+0000] {processor.py:161} INFO - Started process (PID=52268) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:29:33.899+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:29:33.900+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.900+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:29:33.904+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.903+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:33.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:29:33.928+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.041 seconds
[2025-06-19T01:30:03.997+0000] {processor.py:161} INFO - Started process (PID=52304) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:30:03.998+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:30:04.000+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.999+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:30:04.005+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:04.003+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:04.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:30:04.030+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.043 seconds
[2025-06-19T01:30:34.645+0000] {processor.py:161} INFO - Started process (PID=52340) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:30:34.646+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:30:34.649+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.648+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:30:34.657+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.655+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:34.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:30:34.681+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.051 seconds
[2025-06-19T01:31:05.222+0000] {processor.py:161} INFO - Started process (PID=52376) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:31:05.223+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:31:05.224+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:05.224+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:31:05.228+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:05.227+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:05.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:31:05.248+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.038 seconds
[2025-06-19T01:31:35.944+0000] {processor.py:161} INFO - Started process (PID=52412) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:31:35.945+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:31:35.946+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.946+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:31:35.949+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.948+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:35.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:31:35.971+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.037 seconds
[2025-06-19T01:32:06.567+0000] {processor.py:161} INFO - Started process (PID=52448) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:32:06.568+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:32:06.569+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.569+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:32:06.573+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.572+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:06.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:32:06.597+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.041 seconds
[2025-06-19T01:32:37.300+0000] {processor.py:161} INFO - Started process (PID=52484) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:32:37.301+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:32:37.302+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.302+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:32:37.308+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.305+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:37.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:32:37.330+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.040 seconds
[2025-06-19T01:33:07.979+0000] {processor.py:161} INFO - Started process (PID=52520) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:33:07.980+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:33:07.982+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:33:07.986+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.985+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:07.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:33:08.006+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.038 seconds
[2025-06-19T01:33:38.665+0000] {processor.py:161} INFO - Started process (PID=52556) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:33:38.666+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:33:38.667+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:33:38.671+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.670+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:38.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:33:38.693+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.038 seconds
[2025-06-19T01:34:09.477+0000] {processor.py:161} INFO - Started process (PID=52592) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:34:09.478+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:34:09.480+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:34:09.484+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.482+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:09.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:34:09.509+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.044 seconds
[2025-06-19T01:34:40.147+0000] {processor.py:161} INFO - Started process (PID=52628) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:34:40.149+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:34:40.151+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:40.150+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:34:40.155+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:40.154+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:40.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:34:40.179+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.042 seconds
[2025-06-19T01:35:10.902+0000] {processor.py:161} INFO - Started process (PID=52665) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:35:10.903+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:35:10.904+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:35:10.907+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.906+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:35:10.926+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.036 seconds
[2025-06-19T01:35:41.728+0000] {processor.py:161} INFO - Started process (PID=52701) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:35:41.730+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:35:41.731+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.731+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:35:41.736+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.735+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:41.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:35:41.760+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.042 seconds
[2025-06-19T01:36:12.544+0000] {processor.py:161} INFO - Started process (PID=52737) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:36:12.545+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:36:12.546+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.545+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:36:12.549+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.548+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:12.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:36:12.572+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.039 seconds
[2025-06-19T01:36:43.320+0000] {processor.py:161} INFO - Started process (PID=52773) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:36:43.322+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:36:43.323+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.322+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:36:43.326+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.325+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:43.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:36:43.348+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.038 seconds
[2025-06-19T01:37:13.879+0000] {processor.py:161} INFO - Started process (PID=52809) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:37:13.881+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:37:13.883+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.882+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:37:13.887+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.886+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:37:13.911+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.041 seconds
[2025-06-19T01:37:44.749+0000] {processor.py:161} INFO - Started process (PID=52845) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:37:44.750+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:37:44.751+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.751+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:37:44.755+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.754+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:44.756+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:37:44.785+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.049 seconds
[2025-06-19T01:38:15.355+0000] {processor.py:161} INFO - Started process (PID=52881) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:38:15.356+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:38:15.357+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.357+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:38:15.361+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.360+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:15.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:38:15.386+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.040 seconds
[2025-06-19T01:38:46.058+0000] {processor.py:161} INFO - Started process (PID=52918) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:38:46.059+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:38:46.060+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:46.060+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:38:46.064+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:46.063+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:46.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:38:46.085+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.038 seconds
[2025-06-19T01:39:16.687+0000] {processor.py:161} INFO - Started process (PID=52954) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:39:16.688+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:39:16.690+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.689+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:39:16.693+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.692+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:16.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:39:16.713+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.035 seconds
[2025-06-19T01:39:47.293+0000] {processor.py:161} INFO - Started process (PID=52990) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:39:47.294+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:39:47.295+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.295+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:39:47.299+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.298+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:47.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:39:47.319+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.036 seconds
[2025-06-19T01:40:18.035+0000] {processor.py:161} INFO - Started process (PID=53026) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:40:18.036+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:40:18.037+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:18.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:40:18.040+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:18.039+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:18.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:40:18.060+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.036 seconds
[2025-06-19T01:40:48.654+0000] {processor.py:161} INFO - Started process (PID=53062) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:40:48.656+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:40:48.657+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.657+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:40:48.661+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.660+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:48.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:40:48.683+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.040 seconds
[2025-06-19T01:41:19.383+0000] {processor.py:161} INFO - Started process (PID=53098) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:41:19.384+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:41:19.386+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.386+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:41:19.390+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.389+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:19.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:41:19.416+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.046 seconds
[2025-06-19T01:41:50.176+0000] {processor.py:161} INFO - Started process (PID=53134) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:41:50.177+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:41:50.178+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:50.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:41:50.182+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:50.180+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:50.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:41:50.205+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.041 seconds
[2025-06-19T01:42:21.222+0000] {processor.py:161} INFO - Started process (PID=53171) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:42:21.224+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:42:21.227+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.226+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:42:21.233+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.232+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:21.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:42:21.258+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.052 seconds
[2025-06-19T01:42:53.241+0000] {processor.py:161} INFO - Started process (PID=53213) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:42:53.242+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:42:53.243+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.243+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:42:53.247+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.246+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:53.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:42:53.274+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.048 seconds
[2025-06-19T01:43:23.994+0000] {processor.py:161} INFO - Started process (PID=53249) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:43:23.995+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:43:23.996+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.996+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:43:24.000+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.999+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:24.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:43:24.032+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.051 seconds
[2025-06-19T01:43:54.168+0000] {processor.py:161} INFO - Started process (PID=53285) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:43:54.169+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:43:54.170+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:54.170+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:43:54.174+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:54.173+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:54.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:43:54.200+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.043 seconds
[2025-06-19T01:44:24.386+0000] {processor.py:161} INFO - Started process (PID=53321) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:44:24.388+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:44:24.390+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.389+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:44:24.395+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.394+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:24.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:44:24.421+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.050 seconds
[2025-06-19T01:44:54.735+0000] {processor.py:161} INFO - Started process (PID=53358) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:44:54.737+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:44:54.739+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.738+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:44:54.743+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.742+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:54.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:44:54.774+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.053 seconds
[2025-06-19T01:45:25.138+0000] {processor.py:161} INFO - Started process (PID=53394) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:45:25.141+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:45:25.143+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:25.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:45:25.148+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:25.147+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:25.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:45:25.175+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.050 seconds
[2025-06-19T01:45:56.030+0000] {processor.py:161} INFO - Started process (PID=53430) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:45:56.031+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:45:56.033+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:56.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:45:56.039+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:56.037+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:56.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:45:56.079+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.065 seconds
[2025-06-19T01:46:27.214+0000] {processor.py:161} INFO - Started process (PID=53466) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:46:27.232+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:46:27.235+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:27.235+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:46:27.251+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:27.249+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:27.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:46:27.323+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.126 seconds
[2025-06-19T01:46:58.293+0000] {processor.py:161} INFO - Started process (PID=53502) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:46:58.296+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:46:58.302+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:58.301+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:46:58.311+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:58.310+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:58.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:46:58.349+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.069 seconds
[2025-06-19T01:47:29.309+0000] {processor.py:161} INFO - Started process (PID=53538) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:47:29.311+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:47:29.312+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:29.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:47:29.317+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:29.316+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:29.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:47:29.349+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.053 seconds
[2025-06-19T01:47:59.652+0000] {processor.py:161} INFO - Started process (PID=53574) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:47:59.653+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:47:59.655+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:59.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:47:59.659+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:59.658+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:59.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:47:59.690+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.054 seconds
[2025-06-19T01:48:29.956+0000] {processor.py:161} INFO - Started process (PID=53610) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:48:29.957+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:48:29.960+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:29.959+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:48:29.967+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:29.965+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:29.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:48:30.001+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.064 seconds
[2025-06-19T01:49:00.217+0000] {processor.py:161} INFO - Started process (PID=53646) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:49:00.219+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:49:00.220+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:00.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:49:00.225+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:00.224+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:00.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:49:00.253+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.046 seconds
[2025-06-19T01:49:30.715+0000] {processor.py:161} INFO - Started process (PID=53682) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:49:30.717+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:49:30.719+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:30.718+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:49:30.723+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:30.722+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:30.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:49:30.754+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.051 seconds
[2025-06-19T01:50:00.913+0000] {processor.py:161} INFO - Started process (PID=53718) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:50:00.914+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:50:00.916+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:00.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:50:00.921+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:00.920+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:00.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:50:00.947+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.046 seconds
[2025-06-19T01:50:31.321+0000] {processor.py:161} INFO - Started process (PID=53754) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:50:31.323+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:50:31.324+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:31.324+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:50:31.329+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:31.328+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:31.330+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:50:31.357+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.050 seconds
[2025-06-19T01:51:01.455+0000] {processor.py:161} INFO - Started process (PID=53790) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:51:01.456+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:51:01.458+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:01.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:51:01.462+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:01.461+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:01.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:51:01.482+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.038 seconds
[2025-06-19T01:51:32.078+0000] {processor.py:161} INFO - Started process (PID=53827) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:51:32.079+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:51:32.081+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:32.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:51:32.085+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:32.083+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:32.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:51:32.109+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.044 seconds
[2025-06-19T01:52:02.845+0000] {processor.py:161} INFO - Started process (PID=53863) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:52:02.847+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:52:02.848+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:02.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:52:02.853+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:02.852+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:02.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:52:02.877+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.042 seconds
[2025-06-19T01:52:33.316+0000] {processor.py:161} INFO - Started process (PID=53899) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:52:33.317+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:52:33.319+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:33.318+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:52:33.323+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:33.322+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:33.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:52:33.347+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.043 seconds
[2025-06-19T01:53:03.777+0000] {processor.py:161} INFO - Started process (PID=53935) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:53:03.779+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:53:03.780+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:03.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:53:03.784+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:03.783+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:03.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:53:03.805+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.037 seconds
[2025-06-19T01:53:33.975+0000] {processor.py:161} INFO - Started process (PID=53971) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:53:33.976+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:53:33.977+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:33.977+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:53:33.980+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:33.979+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:33.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:53:34.000+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.034 seconds
[2025-06-19T01:54:04.300+0000] {processor.py:161} INFO - Started process (PID=54008) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:54:04.302+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:54:04.304+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:04.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:54:04.309+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:04.307+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:04.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:54:04.331+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.050 seconds
[2025-06-19T01:54:34.703+0000] {processor.py:161} INFO - Started process (PID=54044) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:54:34.704+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:54:34.705+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:34.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:54:34.708+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:34.707+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:34.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:54:34.726+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.032 seconds
[2025-06-19T01:55:05.139+0000] {processor.py:161} INFO - Started process (PID=54080) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:55:05.140+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:55:05.141+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:05.141+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:55:05.144+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:05.143+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:05.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:55:05.165+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.035 seconds
[2025-06-19T01:55:35.363+0000] {processor.py:161} INFO - Started process (PID=54116) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:55:35.365+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:55:35.366+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:35.365+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:55:35.370+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:35.369+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:35.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:55:35.388+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.035 seconds
[2025-06-19T01:56:05.670+0000] {processor.py:161} INFO - Started process (PID=54152) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:56:05.672+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:56:05.674+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:05.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:56:05.678+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:05.677+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:05.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:56:05.697+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.037 seconds
[2025-06-19T01:56:35.941+0000] {processor.py:161} INFO - Started process (PID=54188) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:56:35.942+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:56:35.944+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:35.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:56:35.947+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:35.946+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:35.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:56:35.968+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.038 seconds
[2025-06-19T01:57:06.270+0000] {processor.py:161} INFO - Started process (PID=54224) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:57:06.271+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:57:06.272+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:06.272+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:57:06.276+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:06.275+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:06.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:57:06.296+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.035 seconds
[2025-06-19T01:57:36.820+0000] {processor.py:161} INFO - Started process (PID=54260) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:57:36.822+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:57:36.825+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:36.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:57:36.829+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:36.828+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:36.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:57:36.851+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.041 seconds
[2025-06-19T01:58:07.189+0000] {processor.py:161} INFO - Started process (PID=54296) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:58:07.190+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:58:07.192+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:07.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:58:07.195+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:07.195+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:07.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:58:07.214+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.034 seconds
[2025-06-19T01:58:37.531+0000] {processor.py:161} INFO - Started process (PID=54332) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:58:37.532+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:58:37.533+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:37.533+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:58:37.536+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:37.535+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:37.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:58:37.556+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.035 seconds
[2025-06-19T01:59:07.849+0000] {processor.py:161} INFO - Started process (PID=54368) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:59:07.851+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:59:07.852+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:07.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:59:07.856+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:07.855+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:07.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:59:07.880+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.041 seconds
[2025-06-19T01:59:38.315+0000] {processor.py:161} INFO - Started process (PID=54404) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:59:38.316+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T01:59:38.319+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:38.318+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:59:38.323+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:38.321+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:38.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T01:59:38.342+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.037 seconds
[2025-06-19T02:00:08.651+0000] {processor.py:161} INFO - Started process (PID=54440) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T02:00:08.652+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T02:00:08.653+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:08.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T02:00:08.656+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:08.655+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:08.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T02:00:08.671+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.027 seconds
[2025-06-19T02:00:38.911+0000] {processor.py:161} INFO - Started process (PID=54476) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T02:00:38.912+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py for tasks to queue
[2025-06-19T02:00:38.913+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:38.913+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T02:00:38.917+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:38.916+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py", line 24, in <module>
    from airflow.providers.standard.operators.empty import EmptyOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:38.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py
[2025-06-19T02:00:38.935+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_latest_only.py took 0.034 seconds
