[2025-06-19T01:17:18.770+0000] {processor.py:161} INFO - Started process (PID=51383) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:17:18.771+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:17:18.772+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:18.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:17:18.774+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:18.774+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:18.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:17:18.789+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.026 seconds
[2025-06-19T01:17:49.309+0000] {processor.py:161} INFO - Started process (PID=51419) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:17:49.310+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:17:49.311+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.310+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:17:49.314+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.313+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.315+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:17:49.328+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.031 seconds
[2025-06-19T01:18:19.722+0000] {processor.py:161} INFO - Started process (PID=51455) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:18:19.723+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:18:19.724+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:19.724+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:18:19.727+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:19.726+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:19.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:18:19.744+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.030 seconds
[2025-06-19T01:18:50.255+0000] {processor.py:161} INFO - Started process (PID=51491) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:18:50.256+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:18:50.257+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.257+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:18:50.260+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:50.259+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:50.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:18:50.279+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.032 seconds
[2025-06-19T01:19:21.153+0000] {processor.py:161} INFO - Started process (PID=51533) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:19:21.154+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:19:21.155+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.155+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:19:21.157+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.157+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:19:21.172+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.027 seconds
[2025-06-19T01:19:51.777+0000] {processor.py:161} INFO - Started process (PID=51569) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:19:51.778+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:19:51.779+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:51.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:19:51.782+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:51.781+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:51.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:19:51.797+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.028 seconds
[2025-06-19T01:20:22.191+0000] {processor.py:161} INFO - Started process (PID=51605) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:20:22.192+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:20:22.193+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.193+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:20:22.196+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.195+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:20:22.213+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.029 seconds
[2025-06-19T01:20:52.652+0000] {processor.py:161} INFO - Started process (PID=51641) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:20:52.656+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:20:52.657+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:52.657+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:20:52.661+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:52.660+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:52.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:20:52.680+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.037 seconds
[2025-06-19T01:21:23.124+0000] {processor.py:161} INFO - Started process (PID=51677) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:21:23.125+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:21:23.126+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:21:23.129+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.128+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:23.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:21:23.151+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.035 seconds
[2025-06-19T01:21:54.127+0000] {processor.py:161} INFO - Started process (PID=51713) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:21:54.128+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:21:54.129+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.129+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:21:54.132+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.131+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:21:54.149+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.034 seconds
[2025-06-19T01:22:24.585+0000] {processor.py:161} INFO - Started process (PID=51749) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:22:24.586+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:22:24.587+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:24.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:22:24.590+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:24.589+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:24.590+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:22:24.605+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.029 seconds
[2025-06-19T01:22:55.188+0000] {processor.py:161} INFO - Started process (PID=51785) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:22:55.189+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:22:55.190+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:22:55.193+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.192+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:55.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:22:55.209+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.029 seconds
[2025-06-19T01:23:26.051+0000] {processor.py:161} INFO - Started process (PID=51821) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:23:26.052+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:23:26.052+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:23:26.055+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.054+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:23:26.070+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.027 seconds
[2025-06-19T01:23:56.589+0000] {processor.py:161} INFO - Started process (PID=51857) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:23:56.590+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:23:56.591+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:56.591+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:23:56.594+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:56.593+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:56.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:23:56.619+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.039 seconds
[2025-06-19T01:24:27.264+0000] {processor.py:161} INFO - Started process (PID=51893) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:24:27.266+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:24:27.267+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:24:27.270+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.269+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:27.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:24:27.284+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.028 seconds
[2025-06-19T01:24:57.753+0000] {processor.py:161} INFO - Started process (PID=51929) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:24:57.755+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:24:57.755+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:57.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:24:57.758+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:57.757+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:57.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:24:57.772+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.027 seconds
[2025-06-19T01:25:28.391+0000] {processor.py:161} INFO - Started process (PID=51965) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:25:28.392+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:25:28.393+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:25:28.396+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.396+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:28.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:25:28.413+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.029 seconds
[2025-06-19T01:25:58.947+0000] {processor.py:161} INFO - Started process (PID=52001) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:25:58.948+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:25:58.950+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:58.949+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:25:58.955+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:58.954+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:58.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:25:58.976+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.037 seconds
[2025-06-19T01:26:29.643+0000] {processor.py:161} INFO - Started process (PID=52037) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:26:29.645+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:26:29.647+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:29.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:26:29.660+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:29.655+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:29.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:26:29.722+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.113 seconds
[2025-06-19T01:27:00.243+0000] {processor.py:161} INFO - Started process (PID=52073) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:27:00.244+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:27:00.245+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:27:00.248+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.247+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:27:00.266+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.030 seconds
[2025-06-19T01:27:30.784+0000] {processor.py:161} INFO - Started process (PID=52109) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:27:30.785+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:27:30.786+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:30.786+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:27:30.790+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:30.789+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:30.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:27:30.806+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.030 seconds
[2025-06-19T01:28:01.300+0000] {processor.py:161} INFO - Started process (PID=52145) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:28:01.302+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:28:01.303+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:28:01.307+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.306+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:01.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:28:01.326+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.034 seconds
[2025-06-19T01:28:32.025+0000] {processor.py:161} INFO - Started process (PID=52181) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:28:32.027+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:28:32.028+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.027+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:28:32.032+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.031+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:28:32.054+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.039 seconds
[2025-06-19T01:29:02.735+0000] {processor.py:161} INFO - Started process (PID=52217) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:29:02.736+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:29:02.738+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:02.737+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:29:02.742+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:02.741+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:02.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:29:02.772+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.050 seconds
[2025-06-19T01:29:32.927+0000] {processor.py:161} INFO - Started process (PID=52253) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:29:32.928+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:29:32.930+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:32.929+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:29:32.933+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:32.932+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:32.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:29:32.957+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.039 seconds
[2025-06-19T01:30:03.161+0000] {processor.py:161} INFO - Started process (PID=52289) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:30:03.162+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:30:03.163+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.163+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:30:03.167+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.167+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:03.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:30:03.187+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.037 seconds
[2025-06-19T01:30:33.906+0000] {processor.py:161} INFO - Started process (PID=52325) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:30:33.907+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:30:33.908+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:33.908+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:30:33.911+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:33.910+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:33.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:30:33.930+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.033 seconds
[2025-06-19T01:31:04.404+0000] {processor.py:161} INFO - Started process (PID=52361) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:31:04.405+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:31:04.407+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.406+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:31:04.410+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:04.409+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:04.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:31:04.430+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.035 seconds
[2025-06-19T01:31:35.060+0000] {processor.py:161} INFO - Started process (PID=52397) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:31:35.061+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:31:35.063+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:31:35.066+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.065+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:35.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:31:35.094+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.048 seconds
[2025-06-19T01:32:05.825+0000] {processor.py:161} INFO - Started process (PID=52433) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:32:05.829+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:32:05.831+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:05.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:32:05.835+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:05.834+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:05.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:32:05.856+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.041 seconds
[2025-06-19T01:32:36.492+0000] {processor.py:161} INFO - Started process (PID=52469) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:32:36.493+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:32:36.494+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:36.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:32:36.499+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:36.497+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:36.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:32:36.520+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.041 seconds
[2025-06-19T01:33:07.164+0000] {processor.py:161} INFO - Started process (PID=52505) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:33:07.166+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:33:07.167+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.166+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:33:07.171+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.170+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:07.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:33:07.194+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.042 seconds
[2025-06-19T01:33:37.851+0000] {processor.py:161} INFO - Started process (PID=52541) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:33:37.852+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:33:37.853+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:37.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:33:37.856+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:37.856+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:37.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:33:37.878+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.038 seconds
[2025-06-19T01:34:08.533+0000] {processor.py:161} INFO - Started process (PID=52577) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:34:08.535+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:34:08.537+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:08.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:34:08.541+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:08.540+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:08.542+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:34:08.572+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.053 seconds
[2025-06-19T01:34:39.313+0000] {processor.py:161} INFO - Started process (PID=52613) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:34:39.314+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:34:39.315+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:34:39.319+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.318+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:39.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:34:39.341+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.039 seconds
[2025-06-19T01:35:10.010+0000] {processor.py:161} INFO - Started process (PID=52650) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:35:10.011+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:35:10.011+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.011+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:35:10.014+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.014+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:35:10.035+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.036 seconds
[2025-06-19T01:35:40.800+0000] {processor.py:161} INFO - Started process (PID=52686) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:35:40.801+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:35:40.803+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:40.802+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:35:40.807+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:40.806+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:40.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:35:40.830+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.040 seconds
[2025-06-19T01:36:11.636+0000] {processor.py:161} INFO - Started process (PID=52722) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:36:11.638+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:36:11.639+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:11.639+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:36:11.643+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:11.642+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:11.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:36:11.664+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.040 seconds
[2025-06-19T01:36:42.488+0000] {processor.py:161} INFO - Started process (PID=52758) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:36:42.489+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:36:42.490+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:42.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:36:42.494+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:42.493+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:42.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:36:42.515+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.038 seconds
[2025-06-19T01:37:13.104+0000] {processor.py:161} INFO - Started process (PID=52794) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:37:13.106+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:37:13.108+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:37:13.112+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.111+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:37:13.138+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.045 seconds
[2025-06-19T01:37:43.754+0000] {processor.py:161} INFO - Started process (PID=52830) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:37:43.756+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:37:43.758+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:43.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:37:43.761+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:43.760+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:43.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:37:43.785+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.041 seconds
[2025-06-19T01:38:14.598+0000] {processor.py:161} INFO - Started process (PID=52866) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:38:14.599+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:38:14.600+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:14.600+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:38:14.603+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:14.603+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:14.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:38:14.624+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.036 seconds
[2025-06-19T01:38:45.225+0000] {processor.py:161} INFO - Started process (PID=52903) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:38:45.226+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:38:45.228+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.227+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:38:45.232+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.231+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:45.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:38:45.251+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.036 seconds
[2025-06-19T01:39:15.974+0000] {processor.py:161} INFO - Started process (PID=52939) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:39:15.975+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:39:15.976+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:15.976+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:39:15.980+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:15.979+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:15.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:39:15.999+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.035 seconds
[2025-06-19T01:39:46.461+0000] {processor.py:161} INFO - Started process (PID=52975) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:39:46.462+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:39:46.466+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:46.466+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:39:46.469+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:46.469+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:46.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:39:46.492+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.042 seconds
[2025-06-19T01:40:17.152+0000] {processor.py:161} INFO - Started process (PID=53011) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:40:17.153+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:40:17.155+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:40:17.160+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.159+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:17.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:40:17.186+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.046 seconds
[2025-06-19T01:40:47.841+0000] {processor.py:161} INFO - Started process (PID=53047) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:40:47.842+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:40:47.844+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:47.843+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:40:47.848+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:47.847+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:47.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:40:47.869+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.037 seconds
[2025-06-19T01:41:18.453+0000] {processor.py:161} INFO - Started process (PID=53083) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:41:18.454+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:41:18.457+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:18.456+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:41:18.463+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:18.462+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:18.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:41:18.495+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.057 seconds
[2025-06-19T01:41:49.269+0000] {processor.py:161} INFO - Started process (PID=53119) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:41:49.270+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:41:49.271+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:41:49.276+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.275+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:49.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:41:49.304+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.046 seconds
[2025-06-19T01:42:20.097+0000] {processor.py:161} INFO - Started process (PID=53156) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:42:20.099+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:42:20.100+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:42:20.105+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:20.104+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:20.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:42:20.128+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.044 seconds
[2025-06-19T01:42:50.633+0000] {processor.py:161} INFO - Started process (PID=53192) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:42:50.643+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:42:50.651+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:50.650+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:42:50.670+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:50.668+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:50.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:42:50.721+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.103 seconds
[2025-06-19T01:43:20.997+0000] {processor.py:161} INFO - Started process (PID=53228) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:43:20.999+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:43:21.002+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:21.001+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:43:21.007+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:21.006+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:21.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:43:21.042+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.061 seconds
[2025-06-19T01:43:51.322+0000] {processor.py:161} INFO - Started process (PID=53264) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:43:51.324+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:43:51.325+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:51.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:43:51.329+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:51.328+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:51.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:43:51.356+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.044 seconds
[2025-06-19T01:44:21.422+0000] {processor.py:161} INFO - Started process (PID=53299) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:44:21.425+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:44:21.427+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:21.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:44:21.431+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:21.430+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:21.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:44:21.455+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.045 seconds
[2025-06-19T01:44:51.915+0000] {processor.py:161} INFO - Started process (PID=53336) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:44:51.917+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:44:51.918+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:51.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:44:51.922+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:51.921+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:51.923+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:44:51.948+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.044 seconds
[2025-06-19T01:45:22.270+0000] {processor.py:161} INFO - Started process (PID=53373) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:45:22.271+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:45:22.272+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:22.272+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:45:22.277+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:22.276+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:22.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:45:22.310+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.054 seconds
[2025-06-19T01:45:52.912+0000] {processor.py:161} INFO - Started process (PID=53415) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:45:52.914+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:45:52.917+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:52.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:45:52.923+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:52.922+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:52.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:45:52.957+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.061 seconds
[2025-06-19T01:46:23.535+0000] {processor.py:161} INFO - Started process (PID=53451) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:46:23.538+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:46:23.539+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:23.539+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:46:23.544+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:23.543+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:23.545+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:46:23.576+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.055 seconds
[2025-06-19T01:46:53.827+0000] {processor.py:161} INFO - Started process (PID=53487) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:46:53.829+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:46:53.834+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:53.833+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:46:53.840+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:53.839+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:53.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:46:53.867+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.054 seconds
[2025-06-19T01:47:24.480+0000] {processor.py:161} INFO - Started process (PID=53523) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:47:24.481+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:47:24.483+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:24.482+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:47:24.487+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:24.486+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:24.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:47:24.513+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.044 seconds
[2025-06-19T01:47:54.680+0000] {processor.py:161} INFO - Started process (PID=53559) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:47:54.683+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:47:54.684+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:54.684+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:47:54.690+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:54.688+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:54.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:47:54.723+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.061 seconds
[2025-06-19T01:48:25.088+0000] {processor.py:161} INFO - Started process (PID=53595) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:48:25.089+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:48:25.091+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:25.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:48:25.095+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:25.094+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:25.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:48:25.122+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.045 seconds
[2025-06-19T01:48:55.276+0000] {processor.py:161} INFO - Started process (PID=53631) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:48:55.281+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:48:55.288+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:55.288+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:48:55.301+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:55.300+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:55.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:48:55.344+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.084 seconds
[2025-06-19T01:49:25.743+0000] {processor.py:161} INFO - Started process (PID=53667) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:49:25.745+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:49:25.747+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:25.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:49:25.753+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:25.752+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:25.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:49:25.785+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.055 seconds
[2025-06-19T01:49:56.141+0000] {processor.py:161} INFO - Started process (PID=53703) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:49:56.144+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:49:56.146+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:56.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:49:56.151+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:56.150+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:56.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:49:56.186+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.059 seconds
[2025-06-19T01:50:26.417+0000] {processor.py:161} INFO - Started process (PID=53739) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:50:26.419+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:50:26.420+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:26.420+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:50:26.425+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:26.424+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:26.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:50:26.449+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.044 seconds
[2025-06-19T01:50:56.755+0000] {processor.py:161} INFO - Started process (PID=53775) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:50:56.757+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:50:56.760+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:56.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:50:56.765+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:56.764+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:56.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:50:56.794+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.054 seconds
[2025-06-19T01:51:27.336+0000] {processor.py:161} INFO - Started process (PID=53812) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:51:27.337+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:51:27.338+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:27.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:51:27.343+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:27.342+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:27.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:51:27.369+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.045 seconds
[2025-06-19T01:51:57.991+0000] {processor.py:161} INFO - Started process (PID=53848) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:51:57.992+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:51:57.995+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:57.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:51:58.000+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:57.999+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:58.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:51:58.028+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.049 seconds
[2025-06-19T01:52:28.753+0000] {processor.py:161} INFO - Started process (PID=53884) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:52:28.755+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:52:28.757+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:28.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:52:28.766+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:28.763+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:28.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:52:28.809+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.079 seconds
[2025-06-19T01:52:59.128+0000] {processor.py:161} INFO - Started process (PID=53920) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:52:59.130+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:52:59.131+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:59.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:52:59.136+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:59.135+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:59.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:52:59.162+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.047 seconds
[2025-06-19T01:53:29.454+0000] {processor.py:161} INFO - Started process (PID=53956) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:53:29.456+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:53:29.457+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:29.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:53:29.460+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:29.459+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:29.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:53:29.480+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.034 seconds
[2025-06-19T01:53:59.668+0000] {processor.py:161} INFO - Started process (PID=53993) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:53:59.669+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:53:59.670+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:59.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:53:59.673+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:59.673+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:59.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:53:59.693+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.035 seconds
[2025-06-19T01:54:30.049+0000] {processor.py:161} INFO - Started process (PID=54029) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:54:30.051+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:54:30.052+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:30.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:54:30.056+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:30.056+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:30.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:54:30.078+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.038 seconds
[2025-06-19T01:55:00.451+0000] {processor.py:161} INFO - Started process (PID=54065) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:55:00.453+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:55:00.454+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:00.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:55:00.459+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:00.458+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:00.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:55:00.480+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.039 seconds
[2025-06-19T01:55:30.872+0000] {processor.py:161} INFO - Started process (PID=54101) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:55:30.873+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:55:30.875+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:30.874+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:55:30.879+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:30.878+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:30.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:55:30.901+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.045 seconds
[2025-06-19T01:56:01.037+0000] {processor.py:161} INFO - Started process (PID=54137) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:56:01.039+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:56:01.041+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:01.040+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:56:01.045+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:01.044+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:01.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:56:01.071+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.055 seconds
[2025-06-19T01:56:31.420+0000] {processor.py:161} INFO - Started process (PID=54173) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:56:31.421+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:56:31.423+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:31.422+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:56:31.428+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:31.427+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:31.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:56:31.454+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.045 seconds
[2025-06-19T01:57:01.693+0000] {processor.py:161} INFO - Started process (PID=54209) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:57:01.694+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:57:01.695+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:01.695+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:57:01.698+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:01.697+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:01.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:57:01.719+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.037 seconds
[2025-06-19T01:57:32.090+0000] {processor.py:161} INFO - Started process (PID=54245) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:57:32.094+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:57:32.095+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:32.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:57:32.101+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:32.100+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:32.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:57:32.125+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.045 seconds
[2025-06-19T01:58:02.557+0000] {processor.py:161} INFO - Started process (PID=54281) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:58:02.558+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:58:02.559+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:02.559+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:58:02.562+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:02.562+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:02.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:58:02.582+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.034 seconds
[2025-06-19T01:58:32.924+0000] {processor.py:161} INFO - Started process (PID=54317) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:58:32.925+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:58:32.927+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:32.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:58:32.930+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:32.930+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:32.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:58:32.950+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.035 seconds
[2025-06-19T01:59:03.235+0000] {processor.py:161} INFO - Started process (PID=54353) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:59:03.236+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:59:03.237+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:03.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:59:03.241+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:03.240+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:03.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:59:03.260+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.034 seconds
[2025-06-19T01:59:33.758+0000] {processor.py:161} INFO - Started process (PID=54389) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:59:33.759+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T01:59:33.761+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:33.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:59:33.765+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:33.765+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:33.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T01:59:33.790+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.042 seconds
[2025-06-19T02:00:04.005+0000] {processor.py:161} INFO - Started process (PID=54425) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T02:00:04.006+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T02:00:04.006+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:04.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T02:00:04.009+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:04.009+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:04.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T02:00:04.025+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.030 seconds
[2025-06-19T02:00:34.322+0000] {processor.py:161} INFO - Started process (PID=54461) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T02:00:34.323+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py for tasks to queue
[2025-06-19T02:00:34.324+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:34.324+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T02:00:34.327+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:34.326+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py", line 32, in <module>
    from airflow.providers.standard.operators.python import (
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:34.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py
[2025-06-19T02:00:34.344+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_python_operator.py took 0.031 seconds
