[2025-06-19T01:17:19.181+0000] {processor.py:161} INFO - Started process (PID=51395) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:17:19.182+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:17:19.183+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:17:19.185+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.185+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:19.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:17:19.201+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.027 seconds
[2025-06-19T01:17:49.769+0000] {processor.py:161} INFO - Started process (PID=51431) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:17:49.770+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:17:49.771+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.771+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:17:49.774+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.774+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:17:49.791+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.029 seconds
[2025-06-19T01:18:20.208+0000] {processor.py:161} INFO - Started process (PID=51467) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:18:20.209+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:18:20.210+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.210+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:18:20.213+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.212+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:20.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:18:20.228+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.028 seconds
[2025-06-19T01:18:51.003+0000] {processor.py:161} INFO - Started process (PID=51503) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:18:51.004+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:18:51.004+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.004+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:18:51.007+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.006+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:51.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:18:51.025+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.032 seconds
[2025-06-19T01:19:21.647+0000] {processor.py:161} INFO - Started process (PID=51545) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:19:21.647+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:19:21.648+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.648+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:19:21.651+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.650+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:19:21.666+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.027 seconds
[2025-06-19T01:19:52.237+0000] {processor.py:161} INFO - Started process (PID=51581) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:19:52.238+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:19:52.239+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:19:52.242+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.241+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:52.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:19:52.258+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.028 seconds
[2025-06-19T01:20:22.675+0000] {processor.py:161} INFO - Started process (PID=51617) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:20:22.676+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:20:22.677+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:20:22.681+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.680+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:20:22.695+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.028 seconds
[2025-06-19T01:20:53.094+0000] {processor.py:161} INFO - Started process (PID=51653) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:20:53.094+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:20:53.095+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:20:53.098+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.097+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:53.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:20:53.111+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.025 seconds
[2025-06-19T01:21:23.974+0000] {processor.py:161} INFO - Started process (PID=51689) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:21:23.975+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:21:23.976+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.976+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:21:23.978+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:23.978+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:23.979+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:21:23.996+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.028 seconds
[2025-06-19T01:21:54.573+0000] {processor.py:161} INFO - Started process (PID=51725) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:21:54.574+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:21:54.575+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.575+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:21:54.578+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.577+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:21:54.594+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.028 seconds
[2025-06-19T01:22:25.071+0000] {processor.py:161} INFO - Started process (PID=51761) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:22:25.071+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:22:25.072+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.072+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:22:25.075+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.074+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:25.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:22:25.091+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.028 seconds
[2025-06-19T01:22:55.845+0000] {processor.py:161} INFO - Started process (PID=51797) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:22:55.847+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:22:55.848+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:22:55.851+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:55.850+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:55.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:22:55.869+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.031 seconds
[2025-06-19T01:23:26.497+0000] {processor.py:161} INFO - Started process (PID=51833) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:23:26.499+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:23:26.500+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.499+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:23:26.503+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.502+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:23:26.518+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.029 seconds
[2025-06-19T01:23:57.118+0000] {processor.py:161} INFO - Started process (PID=51869) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:23:57.120+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:23:57.121+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:23:57.124+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.123+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:57.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:23:57.139+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.029 seconds
[2025-06-19T01:24:27.813+0000] {processor.py:161} INFO - Started process (PID=51905) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:24:27.814+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:24:27.815+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.815+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:24:27.818+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:27.817+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:27.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:24:27.834+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.030 seconds
[2025-06-19T01:24:58.274+0000] {processor.py:161} INFO - Started process (PID=51941) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:24:58.275+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:24:58.276+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:24:58.279+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.278+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:58.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:24:58.294+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.028 seconds
[2025-06-19T01:25:28.885+0000] {processor.py:161} INFO - Started process (PID=51977) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:25:28.886+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:25:28.888+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.887+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:25:28.890+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:28.890+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:28.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:25:28.909+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.031 seconds
[2025-06-19T01:25:59.476+0000] {processor.py:161} INFO - Started process (PID=52013) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:25:59.477+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:25:59.477+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:25:59.484+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.482+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:59.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:25:59.506+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.037 seconds
[2025-06-19T01:26:30.345+0000] {processor.py:161} INFO - Started process (PID=52049) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:26:30.346+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:26:30.347+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.347+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:26:30.351+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.349+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:30.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:26:30.371+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.038 seconds
[2025-06-19T01:27:00.768+0000] {processor.py:161} INFO - Started process (PID=52085) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:27:00.768+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:27:00.769+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:27:00.772+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.771+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:27:00.790+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.031 seconds
[2025-06-19T01:27:31.352+0000] {processor.py:161} INFO - Started process (PID=52121) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:27:31.353+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:27:31.354+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:27:31.357+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.356+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:31.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:27:31.375+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.032 seconds
[2025-06-19T01:28:01.920+0000] {processor.py:161} INFO - Started process (PID=52157) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:28:01.922+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:28:01.923+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:28:01.926+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:01.925+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:01.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:28:01.944+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.033 seconds
[2025-06-19T01:28:32.618+0000] {processor.py:161} INFO - Started process (PID=52193) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:28:32.620+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:28:32.621+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.620+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:28:32.624+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.624+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:28:32.644+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.035 seconds
[2025-06-19T01:29:03.517+0000] {processor.py:161} INFO - Started process (PID=52229) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:29:03.519+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:29:03.521+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:29:03.525+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.524+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:03.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:29:03.554+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.052 seconds
[2025-06-19T01:29:33.726+0000] {processor.py:161} INFO - Started process (PID=52265) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:29:33.727+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:29:33.728+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:29:33.733+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.732+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:33.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:29:33.756+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.041 seconds
[2025-06-19T01:30:03.829+0000] {processor.py:161} INFO - Started process (PID=52301) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:30:03.831+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:30:03.832+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.832+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:30:03.836+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:03.834+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:03.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:30:03.857+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.040 seconds
[2025-06-19T01:30:34.494+0000] {processor.py:161} INFO - Started process (PID=52337) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:30:34.495+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:30:34.496+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:30:34.499+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.498+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:34.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:30:34.517+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.031 seconds
[2025-06-19T01:31:05.057+0000] {processor.py:161} INFO - Started process (PID=52373) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:31:05.059+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:31:05.060+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:05.059+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:31:05.064+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:05.062+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:05.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:31:05.088+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.042 seconds
[2025-06-19T01:31:35.776+0000] {processor.py:161} INFO - Started process (PID=52409) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:31:35.777+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:31:35.778+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.778+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:31:35.781+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:35.780+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:35.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:31:35.806+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.041 seconds
[2025-06-19T01:32:06.405+0000] {processor.py:161} INFO - Started process (PID=52445) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:32:06.406+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:32:06.408+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:32:06.412+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.411+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:06.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:32:06.435+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.041 seconds
[2025-06-19T01:32:37.129+0000] {processor.py:161} INFO - Started process (PID=52481) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:32:37.130+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:32:37.131+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:32:37.135+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.134+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:37.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:32:37.156+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.039 seconds
[2025-06-19T01:33:07.822+0000] {processor.py:161} INFO - Started process (PID=52517) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:33:07.823+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:33:07.824+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:33:07.829+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:07.828+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:07.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:33:07.851+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.042 seconds
[2025-06-19T01:33:38.513+0000] {processor.py:161} INFO - Started process (PID=52553) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:33:38.514+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:33:38.515+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.515+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:33:38.518+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.517+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:38.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:33:38.540+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.037 seconds
[2025-06-19T01:34:09.287+0000] {processor.py:161} INFO - Started process (PID=52589) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:34:09.288+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:34:09.289+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:34:09.292+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.291+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:09.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:34:09.319+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.044 seconds
[2025-06-19T01:34:39.990+0000] {processor.py:161} INFO - Started process (PID=52625) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:34:39.991+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:34:39.993+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.992+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:34:39.997+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:39.996+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:39.997+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:34:40.017+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.039 seconds
[2025-06-19T01:35:10.737+0000] {processor.py:161} INFO - Started process (PID=52662) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:35:10.738+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:35:10.740+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.739+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:35:10.744+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.743+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:35:10.765+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.039 seconds
[2025-06-19T01:35:41.549+0000] {processor.py:161} INFO - Started process (PID=52698) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:35:41.551+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:35:41.552+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:35:41.557+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.556+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:41.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:35:41.582+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.043 seconds
[2025-06-19T01:36:12.362+0000] {processor.py:161} INFO - Started process (PID=52734) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:36:12.364+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:36:12.365+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.365+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:36:12.370+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.369+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:12.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:36:12.394+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.045 seconds
[2025-06-19T01:36:43.149+0000] {processor.py:161} INFO - Started process (PID=52770) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:36:43.151+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:36:43.153+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.152+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:36:43.157+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.156+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:43.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:36:43.180+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.041 seconds
[2025-06-19T01:37:13.702+0000] {processor.py:161} INFO - Started process (PID=52806) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:37:13.704+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:37:13.705+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:37:13.709+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.708+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:37:13.732+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.040 seconds
[2025-06-19T01:37:44.550+0000] {processor.py:161} INFO - Started process (PID=52842) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:37:44.552+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:37:44.553+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:37:44.557+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.556+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:44.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:37:44.586+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.049 seconds
[2025-06-19T01:38:15.271+0000] {processor.py:161} INFO - Started process (PID=52878) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:38:15.272+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:38:15.273+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.273+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:38:15.277+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.276+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:15.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:38:15.300+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.040 seconds
[2025-06-19T01:38:45.896+0000] {processor.py:161} INFO - Started process (PID=52915) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:38:45.898+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:38:45.900+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:38:45.904+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:45.903+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:45.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:38:45.925+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.039 seconds
[2025-06-19T01:39:16.517+0000] {processor.py:161} INFO - Started process (PID=52951) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:39:16.518+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:39:16.519+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.519+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:39:16.525+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.523+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:16.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:39:16.550+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.043 seconds
[2025-06-19T01:39:47.132+0000] {processor.py:161} INFO - Started process (PID=52987) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:39:47.133+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:39:47.134+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.133+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:39:47.138+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.136+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:47.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:39:47.159+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.038 seconds
[2025-06-19T01:40:17.870+0000] {processor.py:161} INFO - Started process (PID=53023) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:40:17.871+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:40:17.872+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:40:17.876+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:17.874+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:17.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:40:17.899+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.039 seconds
[2025-06-19T01:40:48.497+0000] {processor.py:161} INFO - Started process (PID=53059) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:40:48.498+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:40:48.500+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.499+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:40:48.505+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.504+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:48.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:40:48.526+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.039 seconds
[2025-06-19T01:41:19.194+0000] {processor.py:161} INFO - Started process (PID=53095) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:41:19.196+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:41:19.197+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:41:19.201+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.200+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:19.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:41:19.234+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.051 seconds
[2025-06-19T01:41:49.992+0000] {processor.py:161} INFO - Started process (PID=53131) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:41:49.994+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:41:49.995+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.995+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:41:49.999+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:49.998+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:50.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:41:50.025+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.043 seconds
[2025-06-19T01:42:21.010+0000] {processor.py:161} INFO - Started process (PID=53168) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:42:21.011+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:42:21.013+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:42:21.017+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.016+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:21.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:42:21.048+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.049 seconds
[2025-06-19T01:42:53.058+0000] {processor.py:161} INFO - Started process (PID=53210) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:42:53.059+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:42:53.060+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.060+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:42:53.065+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.063+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:53.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:42:53.091+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.046 seconds
[2025-06-19T01:43:23.791+0000] {processor.py:161} INFO - Started process (PID=53246) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:43:23.793+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:43:23.795+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.794+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:43:23.798+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:23.797+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:23.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:43:23.823+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.045 seconds
[2025-06-19T01:43:53.974+0000] {processor.py:161} INFO - Started process (PID=53282) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:43:53.976+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:43:53.978+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:53.977+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:43:53.982+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:53.981+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:53.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:43:54.007+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.044 seconds
[2025-06-19T01:44:24.182+0000] {processor.py:161} INFO - Started process (PID=53318) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:44:24.183+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:44:24.185+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:44:24.189+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.188+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:24.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:44:24.216+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.047 seconds
[2025-06-19T01:44:54.622+0000] {processor.py:161} INFO - Started process (PID=53355) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:44:54.624+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:44:54.629+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.629+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:44:54.634+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.633+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:54.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:44:54.660+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.050 seconds
[2025-06-19T01:45:24.937+0000] {processor.py:161} INFO - Started process (PID=53391) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:45:24.939+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:45:24.941+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:24.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:45:24.945+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:24.944+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:24.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:45:24.972+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.049 seconds
[2025-06-19T01:45:55.780+0000] {processor.py:161} INFO - Started process (PID=53427) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:45:55.782+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:45:55.784+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:55.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:45:55.789+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:55.787+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:55.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:45:55.827+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.063 seconds
[2025-06-19T01:46:26.333+0000] {processor.py:161} INFO - Started process (PID=53463) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:46:26.335+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:46:26.337+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:26.336+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:46:26.344+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:26.342+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:26.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:46:26.381+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.063 seconds
[2025-06-19T01:46:56.584+0000] {processor.py:161} INFO - Started process (PID=53499) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:46:56.586+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:46:56.587+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:56.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:46:56.592+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:56.591+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:56.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:46:56.618+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.045 seconds
[2025-06-19T01:47:27.254+0000] {processor.py:161} INFO - Started process (PID=53535) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:47:27.256+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:47:27.258+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:27.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:47:27.264+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:27.263+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:27.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:47:27.295+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.055 seconds
[2025-06-19T01:47:57.518+0000] {processor.py:161} INFO - Started process (PID=53571) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:47:57.519+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:47:57.522+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:57.521+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:47:57.526+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:57.525+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:57.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:47:57.556+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.051 seconds
[2025-06-19T01:48:27.893+0000] {processor.py:161} INFO - Started process (PID=53607) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:48:27.894+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:48:27.895+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:27.895+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:48:27.901+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:27.899+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:27.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:48:27.934+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.056 seconds
[2025-06-19T01:48:58.172+0000] {processor.py:161} INFO - Started process (PID=53643) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:48:58.173+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:48:58.175+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:58.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:48:58.180+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:58.179+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:58.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:48:58.207+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.048 seconds
[2025-06-19T01:49:28.680+0000] {processor.py:161} INFO - Started process (PID=53679) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:49:28.683+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:49:28.685+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:28.684+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:49:28.691+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:28.690+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:28.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:49:28.735+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.073 seconds
[2025-06-19T01:49:59.741+0000] {processor.py:161} INFO - Started process (PID=53715) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:49:59.743+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:49:59.746+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:59.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:49:59.750+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:59.749+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:59.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:49:59.779+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.050 seconds
[2025-06-19T01:50:30.199+0000] {processor.py:161} INFO - Started process (PID=53751) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:50:30.201+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:50:30.203+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:30.203+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:50:30.208+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:30.207+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:30.209+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:50:30.236+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.049 seconds
[2025-06-19T01:51:00.348+0000] {processor.py:161} INFO - Started process (PID=53787) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:51:00.349+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:51:00.351+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:00.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:51:00.356+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:00.354+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:00.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:51:00.385+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.051 seconds
[2025-06-19T01:51:30.971+0000] {processor.py:161} INFO - Started process (PID=53824) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:51:30.972+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:51:30.973+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:30.973+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:51:30.977+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:30.976+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:30.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:51:31.005+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.044 seconds
[2025-06-19T01:52:01.722+0000] {processor.py:161} INFO - Started process (PID=53860) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:52:01.724+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:52:01.726+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:01.725+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:52:01.730+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:01.728+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:01.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:52:01.759+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.050 seconds
[2025-06-19T01:52:32.201+0000] {processor.py:161} INFO - Started process (PID=53896) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:52:32.202+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:52:32.203+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:32.203+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:52:32.207+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:32.206+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:32.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:52:32.228+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.037 seconds
[2025-06-19T01:53:02.653+0000] {processor.py:161} INFO - Started process (PID=53932) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:53:02.654+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:53:02.655+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:02.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:53:02.659+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:02.658+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:02.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:53:02.687+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.050 seconds
[2025-06-19T01:53:32.882+0000] {processor.py:161} INFO - Started process (PID=53968) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:53:32.883+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:53:32.885+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:32.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:53:32.888+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:32.887+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:32.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:53:32.908+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.036 seconds
[2025-06-19T01:54:03.137+0000] {processor.py:161} INFO - Started process (PID=54005) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:54:03.138+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:54:03.139+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:03.139+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:54:03.144+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:03.142+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:03.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:54:03.168+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.040 seconds
[2025-06-19T01:54:33.534+0000] {processor.py:161} INFO - Started process (PID=54041) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:54:33.536+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:54:33.537+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:33.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:54:33.543+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:33.542+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:33.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:54:33.566+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.045 seconds
[2025-06-19T01:55:03.950+0000] {processor.py:161} INFO - Started process (PID=54077) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:55:03.954+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:55:03.957+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:03.957+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:55:03.962+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:03.961+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:03.963+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:55:03.982+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.043 seconds
[2025-06-19T01:55:34.234+0000] {processor.py:161} INFO - Started process (PID=54113) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:55:34.236+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:55:34.237+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:34.237+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:55:34.243+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:34.241+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:34.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:55:34.266+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.042 seconds
[2025-06-19T01:56:04.552+0000] {processor.py:161} INFO - Started process (PID=54149) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:56:04.553+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:56:04.554+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:04.554+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:56:04.558+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:04.558+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:04.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:56:04.581+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.039 seconds
[2025-06-19T01:56:34.850+0000] {processor.py:161} INFO - Started process (PID=54185) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:56:34.851+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:56:34.852+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:34.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:56:34.855+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:34.855+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:34.856+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:56:34.877+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.037 seconds
[2025-06-19T01:57:05.149+0000] {processor.py:161} INFO - Started process (PID=54221) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:57:05.150+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:57:05.151+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:05.151+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:57:05.154+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:05.153+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:05.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:57:05.175+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.035 seconds
[2025-06-19T01:57:35.616+0000] {processor.py:161} INFO - Started process (PID=54257) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:57:35.617+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:57:35.618+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:35.618+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:57:35.623+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:35.622+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:35.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:57:35.643+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.036 seconds
[2025-06-19T01:58:06.069+0000] {processor.py:161} INFO - Started process (PID=54293) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:58:06.071+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:58:06.072+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:06.071+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:58:06.075+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:06.074+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:06.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:58:06.099+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.041 seconds
[2025-06-19T01:58:36.429+0000] {processor.py:161} INFO - Started process (PID=54329) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:58:36.430+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:58:36.432+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:36.431+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:58:36.436+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:36.434+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:36.437+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:58:36.456+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.036 seconds
[2025-06-19T01:59:06.748+0000] {processor.py:161} INFO - Started process (PID=54365) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:59:06.749+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:59:06.750+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:06.749+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:59:06.754+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:06.754+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:06.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:59:06.777+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.039 seconds
[2025-06-19T01:59:37.223+0000] {processor.py:161} INFO - Started process (PID=54401) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:59:37.224+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T01:59:37.225+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:37.225+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:59:37.229+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:37.228+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:37.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T01:59:37.250+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.037 seconds
[2025-06-19T02:00:07.546+0000] {processor.py:161} INFO - Started process (PID=54437) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T02:00:07.548+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T02:00:07.549+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:07.548+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T02:00:07.552+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:07.551+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:07.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T02:00:07.572+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.035 seconds
[2025-06-19T02:00:37.715+0000] {processor.py:161} INFO - Started process (PID=54473) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T02:00:37.717+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py for tasks to queue
[2025-06-19T02:00:37.718+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:37.718+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T02:00:37.722+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:37.721+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py", line 24, in <module>
    from airflow.providers.standard.operators.bash import BashOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:37.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py
[2025-06-19T02:00:37.743+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/standard/example_sensors.py took 0.038 seconds
