[2025-06-19T01:17:19.401+0000] {processor.py:161} INFO - Started process (PID=51400) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:17:19.402+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:17:19.403+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.403+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:17:19.406+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:19.405+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:19.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:17:19.421+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.028 seconds
[2025-06-19T01:17:49.970+0000] {processor.py:161} INFO - Started process (PID=51436) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:17:49.972+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:17:49.973+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:17:49.975+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:17:49.974+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:17:49.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:17:49.990+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.029 seconds
[2025-06-19T01:18:20.487+0000] {processor.py:161} INFO - Started process (PID=51472) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:18:20.488+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:18:20.489+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:18:20.492+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:20.491+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:20.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:18:20.508+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.030 seconds
[2025-06-19T01:18:51.273+0000] {processor.py:161} INFO - Started process (PID=51514) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:18:51.274+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:18:51.275+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.275+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:18:51.278+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:18:51.277+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:18:51.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:18:51.297+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.031 seconds
[2025-06-19T01:19:21.851+0000] {processor.py:161} INFO - Started process (PID=51550) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:19:21.852+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:19:21.853+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.853+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:19:21.856+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:21.855+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:21.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:19:21.873+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.031 seconds
[2025-06-19T01:19:52.441+0000] {processor.py:161} INFO - Started process (PID=51586) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:19:52.442+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:19:52.443+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:19:52.446+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:19:52.445+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:19:52.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:19:52.462+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.028 seconds
[2025-06-19T01:20:22.867+0000] {processor.py:161} INFO - Started process (PID=51622) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:20:22.869+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:20:22.870+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.869+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:20:22.872+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:22.871+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:22.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:20:22.888+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.028 seconds
[2025-06-19T01:20:53.320+0000] {processor.py:161} INFO - Started process (PID=51658) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:20:53.322+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:20:53.323+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:20:53.326+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:20:53.325+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:20:53.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:20:53.340+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.028 seconds
[2025-06-19T01:21:24.169+0000] {processor.py:161} INFO - Started process (PID=51694) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:21:24.170+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:21:24.171+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:24.171+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:21:24.174+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:24.173+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:24.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:21:24.192+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.031 seconds
[2025-06-19T01:21:54.696+0000] {processor.py:161} INFO - Started process (PID=51730) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:21:54.697+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:21:54.698+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:21:54.700+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:21:54.699+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:21:54.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:21:54.715+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.026 seconds
[2025-06-19T01:22:25.278+0000] {processor.py:161} INFO - Started process (PID=51766) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:22:25.279+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:22:25.280+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.280+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:22:25.283+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:25.282+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:25.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:22:25.298+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.027 seconds
[2025-06-19T01:22:56.207+0000] {processor.py:161} INFO - Started process (PID=51802) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:22:56.208+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:22:56.209+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:56.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:22:56.212+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:22:56.211+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:22:56.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:22:56.230+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.029 seconds
[2025-06-19T01:23:26.698+0000] {processor.py:161} INFO - Started process (PID=51838) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:23:26.699+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:23:26.700+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.700+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:23:26.703+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:26.702+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:26.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:23:26.718+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.029 seconds
[2025-06-19T01:23:57.420+0000] {processor.py:161} INFO - Started process (PID=51874) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:23:57.421+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:23:57.421+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:23:57.424+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:23:57.423+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:23:57.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:23:57.439+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.027 seconds
[2025-06-19T01:24:28.020+0000] {processor.py:161} INFO - Started process (PID=51910) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:24:28.022+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:24:28.023+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:28.022+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:24:28.025+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:28.025+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:28.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:24:28.044+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.037 seconds
[2025-06-19T01:24:58.539+0000] {processor.py:161} INFO - Started process (PID=51946) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:24:58.540+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:24:58.541+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.541+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:24:58.544+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:24:58.543+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:24:58.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:24:58.559+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.027 seconds
[2025-06-19T01:25:29.121+0000] {processor.py:161} INFO - Started process (PID=51982) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:25:29.123+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:25:29.123+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:29.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:25:29.126+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:29.125+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:29.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:25:29.143+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.029 seconds
[2025-06-19T01:25:59.762+0000] {processor.py:161} INFO - Started process (PID=52018) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:25:59.764+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:25:59.765+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:25:59.767+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:25:59.767+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:25:59.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:25:59.783+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.029 seconds
[2025-06-19T01:26:30.585+0000] {processor.py:161} INFO - Started process (PID=52054) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:26:30.587+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:26:30.588+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:26:30.591+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:26:30.590+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:26:30.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:26:30.610+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.034 seconds
[2025-06-19T01:27:00.960+0000] {processor.py:161} INFO - Started process (PID=52090) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:27:00.961+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:27:00.962+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.961+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:27:00.965+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:00.964+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:00.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:27:00.981+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.029 seconds
[2025-06-19T01:27:31.559+0000] {processor.py:161} INFO - Started process (PID=52126) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:27:31.560+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:27:31.561+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.561+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:27:31.564+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:27:31.563+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:27:31.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:27:31.583+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.031 seconds
[2025-06-19T01:28:02.207+0000] {processor.py:161} INFO - Started process (PID=52162) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:28:02.209+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:28:02.210+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:02.210+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:28:02.214+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:02.212+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:02.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:28:02.235+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.037 seconds
[2025-06-19T01:28:32.832+0000] {processor.py:161} INFO - Started process (PID=52198) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:28:32.834+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:28:32.834+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:28:32.838+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:28:32.837+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:28:32.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:28:32.856+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.032 seconds
[2025-06-19T01:29:03.823+0000] {processor.py:161} INFO - Started process (PID=52234) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:29:03.824+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:29:03.826+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.826+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:29:03.833+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:03.831+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:03.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:29:03.863+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.052 seconds
[2025-06-19T01:29:33.982+0000] {processor.py:161} INFO - Started process (PID=52270) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:29:33.983+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:29:33.984+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.983+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:29:33.987+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:29:33.986+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:29:33.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:29:34.009+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:30:04.084+0000] {processor.py:161} INFO - Started process (PID=52306) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:30:04.086+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:30:04.088+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:04.087+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:30:04.091+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:04.090+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:04.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:30:04.112+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.037 seconds
[2025-06-19T01:30:34.731+0000] {processor.py:161} INFO - Started process (PID=52342) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:30:34.732+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:30:34.733+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:30:34.736+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:30:34.736+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:30:34.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:30:34.755+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.035 seconds
[2025-06-19T01:31:05.296+0000] {processor.py:161} INFO - Started process (PID=52378) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:31:05.297+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:31:05.298+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:05.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:31:05.302+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:05.301+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:05.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:31:05.321+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.034 seconds
[2025-06-19T01:31:36.118+0000] {processor.py:161} INFO - Started process (PID=52414) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:31:36.119+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:31:36.121+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:36.120+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:31:36.125+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:31:36.124+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:31:36.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:31:36.147+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.041 seconds
[2025-06-19T01:32:06.655+0000] {processor.py:161} INFO - Started process (PID=52450) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:32:06.656+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:32:06.657+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.657+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:32:06.661+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:06.660+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:06.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:32:06.682+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.039 seconds
[2025-06-19T01:32:37.456+0000] {processor.py:161} INFO - Started process (PID=52486) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:32:37.457+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:32:37.459+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.458+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:32:37.463+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:32:37.462+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:32:37.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:32:37.486+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.041 seconds
[2025-06-19T01:33:08.055+0000] {processor.py:161} INFO - Started process (PID=52522) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:33:08.056+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:33:08.057+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:08.056+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:33:08.060+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:08.059+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:08.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:33:08.082+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:33:38.759+0000] {processor.py:161} INFO - Started process (PID=52558) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:33:38.761+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:33:38.762+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.762+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:33:38.767+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:33:38.766+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:33:38.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:33:38.793+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.046 seconds
[2025-06-19T01:34:09.566+0000] {processor.py:161} INFO - Started process (PID=52594) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:34:09.567+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:34:09.568+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.568+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:34:09.572+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:09.571+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:09.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:34:09.605+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.050 seconds
[2025-06-19T01:34:40.231+0000] {processor.py:161} INFO - Started process (PID=52630) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:34:40.233+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:34:40.235+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:40.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:34:40.238+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:34:40.237+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:34:40.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:34:40.262+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.043 seconds
[2025-06-19T01:35:10.976+0000] {processor.py:161} INFO - Started process (PID=52667) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:35:10.978+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:35:10.979+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:35:10.982+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:10.981+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:10.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:35:11.006+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.041 seconds
[2025-06-19T01:35:41.816+0000] {processor.py:161} INFO - Started process (PID=52703) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:35:41.817+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:35:41.818+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.818+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:35:41.822+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:35:41.821+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:35:41.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:35:41.844+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.042 seconds
[2025-06-19T01:36:12.628+0000] {processor.py:161} INFO - Started process (PID=52739) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:36:12.629+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:36:12.630+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.630+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:36:12.634+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:12.633+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:12.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:36:12.665+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.049 seconds
[2025-06-19T01:36:43.474+0000] {processor.py:161} INFO - Started process (PID=52775) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:36:43.476+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:36:43.477+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:36:43.480+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:36:43.479+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:36:43.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:36:43.502+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.039 seconds
[2025-06-19T01:37:13.962+0000] {processor.py:161} INFO - Started process (PID=52811) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:37:13.964+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:37:13.966+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:37:13.970+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:13.969+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:13.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:37:13.992+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.040 seconds
[2025-06-19T01:37:44.842+0000] {processor.py:161} INFO - Started process (PID=52847) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:37:44.844+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:37:44.845+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:37:44.851+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:37:44.849+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:37:44.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:37:44.876+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.048 seconds
[2025-06-19T01:38:15.531+0000] {processor.py:161} INFO - Started process (PID=52883) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:38:15.533+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:38:15.535+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.535+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:38:15.541+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:15.539+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:15.542+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:38:15.567+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.048 seconds
[2025-06-19T01:38:46.144+0000] {processor.py:161} INFO - Started process (PID=52920) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:38:46.146+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:38:46.147+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:46.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:38:46.152+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:38:46.150+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:38:46.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:38:46.174+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.041 seconds
[2025-06-19T01:39:16.835+0000] {processor.py:161} INFO - Started process (PID=52956) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:39:16.836+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:39:16.838+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.837+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:39:16.842+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:16.841+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:16.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:39:16.862+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:39:47.370+0000] {processor.py:161} INFO - Started process (PID=52992) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:39:47.371+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:39:47.373+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:39:47.376+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:39:47.375+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:39:47.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:39:47.398+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:40:18.113+0000] {processor.py:161} INFO - Started process (PID=53028) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:40:18.114+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:40:18.116+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:18.115+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:40:18.119+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:18.118+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:18.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:40:18.139+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.036 seconds
[2025-06-19T01:40:48.731+0000] {processor.py:161} INFO - Started process (PID=53064) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:40:48.732+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:40:48.733+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:40:48.736+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:40:48.735+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:40:48.737+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:40:48.758+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:41:19.464+0000] {processor.py:161} INFO - Started process (PID=53100) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:41:19.466+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:41:19.467+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.467+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:41:19.471+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:19.470+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:19.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:41:19.497+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.043 seconds
[2025-06-19T01:41:50.266+0000] {processor.py:161} INFO - Started process (PID=53136) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:41:50.268+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:41:50.270+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:50.269+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:41:50.273+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:41:50.272+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:41:50.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:41:50.297+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.041 seconds
[2025-06-19T01:42:21.405+0000] {processor.py:161} INFO - Started process (PID=53173) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:42:21.407+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:42:21.409+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:42:21.413+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:21.412+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:21.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:42:21.440+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.048 seconds
[2025-06-19T01:42:53.418+0000] {processor.py:161} INFO - Started process (PID=53215) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:42:53.419+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:42:53.421+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.420+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:42:53.426+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:42:53.424+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:42:53.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:42:53.454+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.049 seconds
[2025-06-19T01:43:24.097+0000] {processor.py:161} INFO - Started process (PID=53251) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:43:24.099+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:43:24.101+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:24.100+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:43:24.106+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:24.105+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:24.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:43:24.135+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.051 seconds
[2025-06-19T01:43:54.353+0000] {processor.py:161} INFO - Started process (PID=53287) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:43:54.355+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:43:54.356+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:54.356+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:43:54.361+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:43:54.360+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:43:54.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:43:54.386+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.045 seconds
[2025-06-19T01:44:24.583+0000] {processor.py:161} INFO - Started process (PID=53323) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:44:24.584+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:44:24.586+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.585+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:44:24.591+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:24.590+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:24.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:44:24.616+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.045 seconds
[2025-06-19T01:44:54.958+0000] {processor.py:161} INFO - Started process (PID=53360) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:44:54.959+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:44:54.960+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:44:54.965+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:44:54.964+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:44:54.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:44:54.997+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.053 seconds
[2025-06-19T01:45:25.251+0000] {processor.py:161} INFO - Started process (PID=53396) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:45:25.252+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:45:25.254+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:25.253+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:45:25.257+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:25.256+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:25.259+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:45:25.286+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.047 seconds
[2025-06-19T01:45:56.162+0000] {processor.py:161} INFO - Started process (PID=53432) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:45:56.164+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:45:56.167+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:56.166+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:45:56.172+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:45:56.170+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:45:56.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:45:56.205+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.059 seconds
[2025-06-19T01:46:27.765+0000] {processor.py:161} INFO - Started process (PID=53468) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:46:27.781+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:46:27.798+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:27.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:46:27.823+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:27.822+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:27.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:46:27.890+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.145 seconds
[2025-06-19T01:46:58.607+0000] {processor.py:161} INFO - Started process (PID=53504) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:46:58.609+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:46:58.610+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:58.610+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:46:58.614+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:46:58.613+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:46:58.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:46:58.656+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.061 seconds
[2025-06-19T01:47:29.422+0000] {processor.py:161} INFO - Started process (PID=53540) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:47:29.424+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:47:29.426+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:29.425+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:47:29.431+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:29.430+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:29.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:47:29.461+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.052 seconds
[2025-06-19T01:47:59.761+0000] {processor.py:161} INFO - Started process (PID=53576) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:47:59.763+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:47:59.765+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:59.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:47:59.770+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:47:59.768+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:47:59.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:47:59.801+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.053 seconds
[2025-06-19T01:48:30.079+0000] {processor.py:161} INFO - Started process (PID=53612) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:48:30.081+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:48:30.083+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:30.082+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:48:30.089+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:48:30.087+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:48:30.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:48:30.121+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.055 seconds
[2025-06-19T01:49:00.321+0000] {processor.py:161} INFO - Started process (PID=53648) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:49:00.323+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:49:00.325+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:00.324+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:49:00.330+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:00.329+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:00.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:49:00.360+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.051 seconds
[2025-06-19T01:49:30.823+0000] {processor.py:161} INFO - Started process (PID=53684) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:49:30.825+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:49:30.827+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:30.826+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:49:30.831+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:49:30.830+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:49:30.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:49:30.861+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.051 seconds
[2025-06-19T01:50:01.014+0000] {processor.py:161} INFO - Started process (PID=53720) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:50:01.016+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:50:01.017+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:01.017+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:50:01.023+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:01.021+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:01.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:50:01.059+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.056 seconds
[2025-06-19T01:50:32.344+0000] {processor.py:161} INFO - Started process (PID=53756) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:50:32.346+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:50:32.347+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:32.347+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:50:32.351+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:50:32.350+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:50:32.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:50:32.377+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.044 seconds
[2025-06-19T01:51:02.481+0000] {processor.py:161} INFO - Started process (PID=53792) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:51:02.483+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:51:02.484+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:02.484+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:51:02.488+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:02.487+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:02.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:51:02.514+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.043 seconds
[2025-06-19T01:51:33.110+0000] {processor.py:161} INFO - Started process (PID=53829) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:51:33.112+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:51:33.113+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:33.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:51:33.118+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:51:33.116+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:51:33.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:51:33.145+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.048 seconds
[2025-06-19T01:52:03.869+0000] {processor.py:161} INFO - Started process (PID=53865) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:52:03.871+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:52:03.873+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:03.873+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:52:03.877+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:03.876+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:03.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:52:03.904+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.046 seconds
[2025-06-19T01:52:34.381+0000] {processor.py:161} INFO - Started process (PID=53901) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:52:34.382+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:52:34.383+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:34.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:52:34.388+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:52:34.386+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:52:34.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:52:34.409+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:53:04.803+0000] {processor.py:161} INFO - Started process (PID=53937) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:53:04.804+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:53:04.805+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:04.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:53:04.808+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:04.807+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:04.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:53:04.830+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.037 seconds
[2025-06-19T01:53:35.045+0000] {processor.py:161} INFO - Started process (PID=53973) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:53:35.047+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:53:35.047+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:35.047+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:53:35.051+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:53:35.050+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:53:35.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:53:35.071+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.035 seconds
[2025-06-19T01:54:05.323+0000] {processor.py:161} INFO - Started process (PID=54010) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:54:05.324+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:54:05.325+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:05.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:54:05.328+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:05.328+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:05.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:54:05.347+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.035 seconds
[2025-06-19T01:54:35.753+0000] {processor.py:161} INFO - Started process (PID=54046) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:54:35.754+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:54:35.756+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:35.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:54:35.761+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:54:35.760+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:54:35.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:54:35.789+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.046 seconds
[2025-06-19T01:55:06.157+0000] {processor.py:161} INFO - Started process (PID=54082) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:55:06.158+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:55:06.159+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:06.159+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:55:06.163+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:06.162+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:06.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:55:06.185+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:55:36.360+0000] {processor.py:161} INFO - Started process (PID=54118) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:55:36.362+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:55:36.363+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:36.363+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:55:36.368+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:55:36.367+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:55:36.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:55:36.390+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.040 seconds
[2025-06-19T01:56:06.745+0000] {processor.py:161} INFO - Started process (PID=54154) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:56:06.747+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:56:06.748+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:06.748+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:56:06.755+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:06.754+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:06.756+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:56:06.774+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:56:36.966+0000] {processor.py:161} INFO - Started process (PID=54190) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:56:36.968+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:56:36.969+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:36.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:56:36.972+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:56:36.971+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:56:36.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:56:36.991+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.034 seconds
[2025-06-19T01:57:07.340+0000] {processor.py:161} INFO - Started process (PID=54226) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:57:07.341+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:57:07.343+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:07.342+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:57:07.346+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:07.345+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:07.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:57:07.365+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.034 seconds
[2025-06-19T01:57:37.852+0000] {processor.py:161} INFO - Started process (PID=54262) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:57:37.853+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:57:37.855+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:37.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:57:37.859+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:57:37.858+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:57:37.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:57:37.878+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.037 seconds
[2025-06-19T01:58:08.263+0000] {processor.py:161} INFO - Started process (PID=54298) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:58:08.264+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:58:08.265+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:08.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:58:08.269+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:08.268+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:08.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:58:08.290+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.036 seconds
[2025-06-19T01:58:38.555+0000] {processor.py:161} INFO - Started process (PID=54334) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:58:38.556+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:58:38.557+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:38.557+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:58:38.561+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:58:38.560+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:58:38.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:58:38.582+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.038 seconds
[2025-06-19T01:59:08.922+0000] {processor.py:161} INFO - Started process (PID=54370) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:59:08.923+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:59:08.924+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:08.924+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:59:08.928+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:08.927+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:08.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:59:08.949+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.037 seconds
[2025-06-19T01:59:39.351+0000] {processor.py:161} INFO - Started process (PID=54406) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:59:39.353+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T01:59:39.354+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:39.353+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:59:39.357+0000] {logging_mixin.py:188} INFO - [2025-06-19T01:59:39.356+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T01:59:39.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T01:59:39.378+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.036 seconds
[2025-06-19T02:00:09.715+0000] {processor.py:161} INFO - Started process (PID=54442) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T02:00:09.715+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T02:00:09.716+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:09.716+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T02:00:09.719+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:09.718+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:09.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T02:00:09.733+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.026 seconds
[2025-06-19T02:00:39.944+0000] {processor.py:161} INFO - Started process (PID=54478) to work on /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T02:00:39.945+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py for tasks to queue
[2025-06-19T02:00:39.947+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:39.946+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T02:00:39.950+0000] {logging_mixin.py:188} INFO - [2025-06-19T02:00:39.949+0000] {dagbag.py:355} ERROR - Failed to import: /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py", line 23, in <module>
    from airflow.providers.standard.triggers.file import FileDeleteTrigger
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/__init__.py", line 37, in <module>
    raise RuntimeError(
RuntimeError: The package `apache-airflow-providers-standard:1.3.0` needs Apache Airflow 2.10.0+
[2025-06-19T02:00:39.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py
[2025-06-19T02:00:39.977+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.12/site-packages/airflow/example_dags/example_asset_with_watchers.py took 0.044 seconds
